# Generated by Django 5.1.3 on 2024-11-27 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaignresult',
            name='recording',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
